# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
    ]
